#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = remove ] || [ "$1" = upgrade ] && \
   which install-docs >/dev/null 2>&1; then
	install-docs -r blueproximity-plus
fi
# End automatically added section
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c -b blueproximity-plus.dirs
fi
# End automatically added section
if [ -e ~/.config/autostart/blueproximity-plus.desktop ]; then
	rm  ~/.config/autostart/blueproximity-plus.desktop || true
fi

