#!/bin/sh
set -e
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Cleanup startup config files if remnant available
CONFIG1=/etc/xdg/autostart/blueproximity-plus-autostart.desktop
if [ -e $CONFIG1 ]; then
    rm $CONFIG1
fi
# Cleanup done

